name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bsalunke/test-github-action:1.0
    - name: Docker Push
      run: docker push bsalunke/test-github-action:1.0  
    - uses: actions/test-cs-action@ac4fea93700f2a00c14b9df63d17e56ee99207ba
      with: 
        image: bsalunke/test-github-action:1.0
        purl: ${{secrets.PURL}}
        ai: ${{secrets.AI}}
        ci: ${{secrets.CI}}

 
